#!/bin/sh
set -e
dir=$(cd ${0%/*} 2>/dev/null; pwd)
mkdir ${dir}/../gen-voice-minimal
cd ${dir}/../gen-voice-minimal
mkdir clips

#python3 ${dir}/mk-voice-minimal-test1.py > list.txt
${dir}/mk-voice-minimal-test2 < ${dir}/mk-voice-minimal-test2.txt > list.txt

while read n line; do
    f="$n-espeak.wav"
    echo $f
    espeak -p 60 -s 130 -w "clips/$f" "$line"
    lame --preset voice "clips/$f"
    rm -f "clips/$f"
done < list.txt
